---
- name: NXOS-FACTS
  nxos_facts:
    gather_subset: all
  register: output
  tags: main

- name: HOSTNAME
  debug: msg="{{ output.ansible_facts['ansible_net_hostname'] }}"
  tags: main

- set_fact:
    hostname: "{{ output.ansible_facts['ansible_net_hostname'] }}"
  tags: main

- name: CONFIG ERT01.MED2
  include_tasks: ert01_med2.yml
  when: hostname == 'ert01.med2'
  tags: main

- name: CONFIG ERT01.CLT1
  include_tasks: ert01_clt1.yml
  when: hostname == 'ert01.clt1'
  tags: main
