---

- name: GATHER LIST OF INTERFACES
  nxos_command:
    commands:
      - show cdp neighbors | json-pretty
  register: list

- name: DETERMINE AMOUNT OF CDP NEIGHBORS
  nxos_command:
    commands:
      - show cdp neighbors | i Eth|mgmt | count
  register: count

- set_fact:
    AMOUNT="{{ count.stdout_lines[0] | int }}"

- debug:
    msg="{{AMOUNT}}"

- debug:
    var: item
  loop: "{{ list.stdout[0] | json_query('TABLE_cdp_neighbor_brief_info.ROW_cdp_neighbor_brief_info[*].intf_id') }}"
  register: local

- debug:
    var: item
  loop: "{{ list.stdout[0] | json_query('TABLE_cdp_neighbor_brief_info.ROW_cdp_neighbor_brief_info[*].device_id') }}"
  register: neighbor

- debug:
    var: item
  loop: "{{ list.stdout[0] | json_query('TABLE_cdp_neighbor_brief_info.ROW_cdp_neighbor_brief_info[*].port_id') }}"
  register: neighbor_port

- name: ONE LOCAL INTERFACES
  include_tasks: one.yml
  when: AMOUNT ==  "{{ 1 }}"

- name: TWO LOCAL INTERFACES
  include_tasks: two.yml
  when: AMOUNT ==  "{{ 2 }}"

- name: THREE LOCAL INTERFACES
  include_tasks: three.yml
  when: AMOUNT ==  "{{ 3 }}"

- name: FOUR LOCAL INTERFACES
  include_tasks: four.yml
  when: AMOUNT ==  "{{ 4 }}"

- name: FIVE LOCAL INTERFACES
  include_tasks: five.yml
  when: AMOUNT ==  "{{ 5 }}"

- name: SIX LOCAL INTERFACES
  include_tasks: six.yml
  when: AMOUNT ==  "{{ 6 }}"
