---
# tasks file for roles/vty
  - name: GATHER VTY INFO => iosxr
    iosxr_command:
      commands:
        - show run | include access-class
    #when: OSFOUND == 'iosxr' or OSFOUND == 'iosxr-xe'
    register: findvty
    #tags: vty

  - debug: msg="{{findvty.stdout_lines}}"
    #tags: vty

  - set_fact: pattern="ingress (\w+)"
    #tags: vty

  - name: SETTING MATCH VAR
    set_fact: MATCH="{{findvty.stdout[0] | regex_search(pattern) | replace('ingress ', '')}}"
    #tags: vty

  - debug: var=MATCH
    #tags: vty

  - name: CURRENT VTY ACL
    iosxr_command:
      commands: "show access-list {{ MATCH }}"
    #when: OSFOUND == 'iosxr'
    register: beforeacl
    #tags: vty

  - debug: msg="{{beforeacl.stdout_lines}}"
    #tags: vty

###### PUSH CONFIGURE #######
  - name: REMOVE OLD VTY ACCESS_CLASS
    iosxr_config:
      lines:
        - "no access-class ingress {{ MATCH }}"
      parents: ['line default']
      match: exact
    when: "'{{ MATCH }}' != None"
    #when: OSFOUND == 'iosxr'

  - name: REMOVE OLD ACL
    iosxr_config:
      lines:
        - "no ipv4 access-list {{ MATCH }}"
    when: "'{{ MATCH }}' != None"

  - name: CREATING NEW VTY ACL
    iosxr_config:
      lines:
        - "ipv4 access-list VTY_ACCESS_ACL"
      match: exact
    #when: {{ MATCH }} != 'VTY_ACCESS_ACL'
    #when: OSFOUND == 'iosxr'

  - name: ADDING ACL TO ACCESS_LIST
    iosxr_config:
      lines:  "{{ item }}"
      parents: ['ipv4 access-list VTY_ACCESS_ACL']
      match: exact
    with_items: "{{ VTY_ACCESS_ACL_IOSXR }}"
    #when: OSFOUND == 'iosxr'

  - name: APPLY NEW ACL TO VTY LINES => iosxr
    iosxr_config:
      lines:
        - access-class ingress VTY_ACCESS_ACL
      parents: ['line default']

#   - name: APPLY NEW ACL TO VTY LINES 0 5 => iosxr
#     iosxr_config:
#       lines:
#         - access-class VTY_ACCESS_ACL in
#       parents: ['line vty 5 15']
#       save_when: always
#     tags: save

  - name: CHECK ACLs
    iosxr_command:
      commands:
        - show access-list VTY_ACCESS_ACL
        - show run | i access-class
    #when: OSFOUND == 'iosxr'
    register: afteracl

  - debug: var=afteracl.stdout_lines
