---
# tasks file for checklist
- name: GATHER VTY FACTS
  nxos_command:
    commands: show run | sec line
    wait_for: result[0] contains access-class
    match: any
  register: output

# - set_fact:
#     VTY_ACL: "{{ output.stdout_lines | regex_search(regexp) }}"
#   vars:
#     regexp: 'access-class\s+\b(\w+)\b'

# - name: CURRENT VTY ACL
#   debug:
#     var: VTY_ACL

- name: CURRENT VTY ACL
  debug: msg="{{ output.stdout_lines }}"

# - name: REMOVE OLD VTY ACL
#   nxos_config:
#     lines:
#       - no access-class "{{ VTY_ACL }}"
#       - no access-list "{{ VTY_ACL }}"



# -name: APPLY NEW ACL TO VTY LINES
#  nxos_config:
#    lines:
#      - configure terminal
#      - line vty
#      - access-class VTY_ACCESS_ACL

# -name: GATHER NEW VTY LINE FACTS
#  nxos_command:
#    commands: show run | sec line
#  register: output

# -name: VERIFY NEW VTY CONFIG
#  debug: msg="{{ output.stdout_lines }}"

# -name: SAVE CONFIG
#  nxos_config:
#    lines:
#      - save
