---
# tasks file for ios_upgrade
- name: Include Login Credentials
  include_vars: providers.yml

- name: VERIFYING CONNECTIVITY
  wait_for:
       port: 22
       host: "{{inventory_hostname}}"
       timeout: 5

- name: IOS-FACTS
  ios_facts:
    gather_subset: all
  register: output
  tags: current
# Working
# - name: Debug output_format
#   debug: msg="{{output}}"

- name: SERIAL ....
  debug: msg="{{ output.ansible_facts['ansible_net_serialnum'] }}"

- name: TOTAL MEMORY ....
  debug: msg="{{ output.ansible_facts['ansible_net_memtotal_mb'] }}"

- name: FREE MEMORY ....
  debug: msg="{{ output.ansible_facts['ansible_net_memfree_mb'] }}"

- name: CURRENT VERSION ....
  debug: msg="{{ output.ansible_facts['ansible_net_version'] }}"

- name: FREE FLASH ....
  debug: msg="{{ output.ansible_facts[ 'ansible_net_flashfree_mb'] }}"

- set_fact:
    currentversion: "{{ output.ansible_facts['ansible_net_version'] }}"
    currentfreemem: "{{ output.ansible_facts['ansible_net_memfree_mb'] }}"
    currentfreeflash: "{{ output.ansible_facts['ansible_net_flashfree_mb'] }}"
  tags:	current

- name: CURRENT IMAGE INSTALLED ....
  debug: msg="{{ output.ansible_facts['ansible_net_image'] }}"

- name: COPYING IMAGE TO DEVICE FLASH
  ntc_file_copy:
    platform: cisco_ios_ssh
    local_file: "{{ fullpath }}"
    provider: "{{ ios }}"
  when: (currentfreeflash > 20786 and currentversion != "{{ version }}")
  tags: copy

- name: SETTING BOOT IMAGE
  ios_config:
     lines:
       - no boot system
       - boot system "{{ newimage }}"
     provider: "{{ cisco }}"
     host: "{{ inventory_hostname }}"
  when: currentversion != "{{ version }}"
  tags: current, save

- name: SAVING CONFIGS
  ntc_save_config:
      platform: cisco_ios_ssh
      local_file: "{{ backuppath }}"
      provider: "{{ ios }}"
  #when: currentversion != "{{ version }}"
  tags: backup
# #
# - name: RELOADING THE DEVICE
#   ntc_reboot:
#     platform: cisco_ios_ssh
#     confirm: true
#     timer: 2
#   when: currentversion != "{{ version }}"
#   tags: reload
#
# - name: VERIFYING CONNECTIVITY
#   wait_for:
#        port: 22
#        host: "{{inventory_hostname}}"
#        timeout: 300
#
# - name: DELTE .BIN FILE from FLASH
#   ios_config:
#      lines:: delete /recursive /force flash:{{ newimage }}
#      provider: "{{ ios }}"
#      host: "{{ inventory_hostname }}"
#   when: currentversion == "{{ version }}"
#   #register: result
#   tags: delete
