---

- set_fact:
    local1="{{local.results[0].item[0:] | replace('GigabitEthernet','Gi') | replace ('Ethernet','Eth') }}"
    local2="{{local.results[1].item[0:] | replace('GigabitEthernet','Gi') | replace ('Ethernet','Eth') }}"
    local3="{{local.results[2].item[0:] | replace('GigabitEthernet','Gi') | replace ('Ethernet','Eth') }}"
    local4="{{local.results[3].item[0:] | replace('GigabitEthernet','Gi') | replace ('Ethernet','Eth') }}"
  register: four_interfaces

- debug:
    msg="{{four_interfaces}}"

- set_fact:
    neighbor1="{{neighbor.results[0].item[0:] | replace('.net.bamtech.co','') | replace ('(*)','') }}"
    neighbor2="{{neighbor.results[1].item[0:] | replace('.net.bamtech.co','') | replace ('(*)','') }}"
    neighbor3="{{neighbor.results[2].item[0:] | replace('.net.bamtech.co','') | replace ('(*)','') }}"
    neighbor4="{{neighbor.results[3].item[0:] | replace('.net.bamtech.co','') | replace ('(*)','') }}"
  register: four_neighbors

- debug:
    msg="{{four_neighbors}}"

- set_fact:
    neighbor_port1="{{neighbor_port.results[0].item[0:] | replace('GigabitEthernet','Gi') | replace ('Ethernet','Eth') }}"
    neighbor_port2="{{neighbor_port.results[1].item[0:] | replace('GigabitEthernet','Gi') | replace ('Ethernet','Eth') }}"
    neighbor_port3="{{neighbor_port.results[2].item[0:] | replace('GigabitEthernet','Gi') | replace ('Ethernet','Eth') }}"
    neighbor_port4="{{neighbor_port.results[3].item[0:] | replace('GigabitEthernet','Gi') | replace ('Ethernet','Eth') }}"
  register: four_neighbor_ports

- debug:
    msg="{{four_neighbor_ports}}"

- name: VERIFY CURRENT LOCAL INTERFACE DESCRIPTIONS
  nxos_command:
    commands:
      - show interface status | i "{{ local1 }}" | awk '{print $2}'
  register: current1

- name: VERIFY CURRENT LOCAL INTERFACE DESCRIPTIONS
  nxos_command:
    commands:
      - show interface status | i "{{ local2 }}" | awk '{print $2}'
  register: current2

- name: VERIFY CURRENT LOCAL INTERFACE DESCRIPTIONS
  nxos_command:
    commands:
      - show interface status | i "{{ local3 }}" | awk '{print $2}'
  register: current3

- name: VERIFY CURRENT LOCAL INTERFACE DESCRIPTIONS
  nxos_command:
    commands:
      - show interface status | i "{{ local4 }}" | awk '{print $2}'
  register: current4

- set_fact:
    interface1_description="{{neighbor1}}_{{neighbor_port1}}"

- debug:
    msg="{{interface1_description}}"

- set_fact:
    interface2_description="{{neighbor2}}_{{neighbor_port2}}"

- debug:
    msg="{{interface2_description}}"

- set_fact:
    interface3_description="{{neighbor3}}_{{neighbor_port3}}"

- debug:
    msg="{{interface3_description}}"

- set_fact:
    interface4_description="{{neighbor4}}_{{neighbor_port4}}"

- debug:
    msg="{{interface4_description}}"

- name: CONFIG DESCRIPTION ON LOCAL INTERFACE
  nxos_config:
    lines:
      - description {{ interface1_description }}
    parents: "interface {{ local1 }}"
  when: current1.stdout[0] == "--"

- name: CONFIG DESCRIPTION ON LOCAL INTERFACE
  nxos_config:
    lines:
      - description {{ interface2_description }}
    parents: "interface {{ local2 }}"
  when: current2.stdout[0] == "--"

- name: CONFIG DESCRIPTION ON LOCAL INTERFACE
  nxos_config:
    lines:
      - description {{ interface3_description }}
    parents: "interface {{ local3 }}"
  when: current3.stdout[0] == "--"

- name: CONFIG DESCRIPTION ON LOCAL INTERFACE
  nxos_config:
    lines:
      - description {{ interface4_description }}
    parents: "interface {{ local4 }}"
  when: current4.stdout[0] == "--"
