---
- hosts: "{{ host }}"
  gather_facts: no
  vars:
    - user: "{{ lookup('env','USER') }}" 
  vars_files:
    - /home/{{user}}/.cred
    #- ../playbook/providers.yml
    - ../group_vars/ios.yml
    - ../group_vars/nxos.yml
    - ../group_vars/common.yml
    - ../group_vars/asa.yml
  roles:
    #- ios_upgrade
    - baseline_vty
    #- baseline_snmp
    #- baseline_user
