---
ansible_connection: local
ansible_network_os: ios
#ansible_user: mmehta
ansible_become: yes
ansible_become_method: enable
#ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q nms01.mlbam.net"'
cisco:
  host: "{{ inventory_hostname }}"
  username: "{{ username }}"
  password: "{{ password }}"
  #transport: cli
ios:
  host: "{{ inventory_hostname }}"
  username: "{{ username }}"
  password: "{{ password }}"
  transport: cli
  connection: ssh
